version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=platziverse
      - POSTGRES_USER=platzi
      - POSTGRES_PASSWORD=platzi
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
